// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A CV parsing AI agent.
 *
 * - parseCv - A function that handles the CV parsing process.
 * - ParseCvInput - The input type for the parseCv function.
 * - ParseCvOutput - The return type for the parseCv function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ParseCvInputSchema = z.object({
  cvDataUri: z
    .string()
    .describe(
      "The CV PDF file as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ParseCvInput = z.infer<typeof ParseCvInputSchema>;

const ParseCvOutputSchema = z.object({
  bio: z.string().describe('A short biography of the person.'),
  skills: z.object({
    hardSkills: z.array(z.string()).describe('A list of hard skills.'),
    softSkills: z.array(z.string()).describe('A list of soft skills.'),
    tools: z.array(z.string()).describe('A list of tools.'),
  }).describe('The skills of the person.'),
  certifications: z.array(z.string()).describe('A list of certifications.'),
});
export type ParseCvOutput = z.infer<typeof ParseCvOutputSchema>;

export async function parseCv(input: ParseCvInput): Promise<ParseCvOutput> {
  return parseCvFlow(input);
}

const prompt = ai.definePrompt({
  name: 'parseCvPrompt',
  input: {schema: ParseCvInputSchema},
  output: {schema: ParseCvOutputSchema},
  prompt: `You are an expert CV parser. You will extract the following information from the CV: bio, skills (hard skills, soft skills, tools), and certifications.

  Here is the CV:

  {{media url=cvDataUri}}
  `,
});

const parseCvFlow = ai.defineFlow(
  {
    name: 'parseCvFlow',
    inputSchema: ParseCvInputSchema,
    outputSchema: ParseCvOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
