// This is an autogenerated file from Firebase Studio.
import { config } from 'dotenv';
config();

// Import the flows you are actively working on here.
// For example:
// import '@/ai/flows/cv-parsing.ts';
// import '@/ai/flows/tag-image.ts';
